TSD/TSD_Rails-main/config/routes.rb
Rails.application.routes.draw do
  resources :ingredients, only: :create
  resources :recipes
  devise_for :users
  root "hello#index"
end

TSD/TSD_Rails-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

TSD/TSD_Rails-main/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  has_one_attached :photo
end

TSD/TSD_Rails-main/app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :ingredients, dependent: :destroy
  has_rich_text :content
  validate :ingredients_count

  private

  def ingredients_count
    errors.add(:base, "A recipe can have at most 3 ingredients") if ingredients.size > 3
  end
end

TSD/TSD_Rails-main/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

TSD/TSD_Rails-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to @recipe
  end
end

TSD/TSD_Rails-main/app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

TSD/TSD_Rails-main/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
  
    respond_to do |format|
      if @ingredient.recipe.nil?
        format.html { redirect_to request.referrer, alert: "Can't add ingredient to recipe - The recipe does not exist." }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      elsif @ingredient.recipe.ingredients.count >= 3
        format.html { redirect_to recipe_url(@ingredient.recipe), alert: "A recipe can have at most 3 ingredients." }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      elsif @ingredient.save
        format.html { redirect_to recipe_url(@ingredient.recipe), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :quantity, :recipe_id, :photo)
    end
end

TSD/TSD_Rails-main/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @ingredient = Ingredient.new(recipe: @recipe)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new(creator: current_user)
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    authorize @recipe
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, :creator_id, :content)
    end
end

TSD/TSD_Rails-main/app/helpers/application_helper.rb
module ApplicationHelper
end

TSD/TSD_Rails-main/app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

TSD/TSD_Rails-main/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

TSD/TSD_Rails-main/app/helpers/recipes_helper.rb
module RecipesHelper
end

TSD/TSD_Rails-main/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

TSD/TSD_Rails-main/app/views/hello/index.html.erb
<div class="App">
  <header class="App-header">
    <img src="Octocat.png" class="App-logo" alt="logo" />
    <p>
      GitHub Codespaces <span class="heart">♥️</span> Rails
    </p>
    <p class="small">
      Edit <code>app/views/hello/index.html.erb</code> and see changes live!
    </p>
  </header>
</div>

TSD/TSD_Rails-main/app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, class: "contents") do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="my-5">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :recipe_id %>
    <%= form.text_field :recipe_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

TSD/TSD_Rails-main/app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= ingredient.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= ingredient.quantity %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Recipe:</strong>
    <%= ingredient.recipe_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this ingredient", ingredient, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this ingredient', edit_ingredient_path(ingredient), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

TSD/TSD_Rails-main/app/views/ingredients/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ingredient</h1>

  <%= render "form", ingredient: @ingredient %>

  <%= link_to "Show this ingredient", @ingredient, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to ingredients", ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

TSD/TSD_Rails-main/app/views/ingredients/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ingredients</h1>
    <%= link_to 'New ingredient', new_ingredient_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="ingredients" class="min-w-full">
    <%= render @ingredients %>
  </div>
</div>

TSD/TSD_Rails-main/app/views/ingredients/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ingredient</h1>

  <%= render "form", ingredient: @ingredient %>

  <%= link_to 'Back to ingredients', ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

TSD/TSD_Rails-main/app/views/ingredients/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ingredient %>

    <%= link_to 'Edit this ingredient', edit_ingredient_path(@ingredient), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this ingredient', ingredient_path(@ingredient), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to ingredients', ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

TSD/TSD_Rails-main/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

TSD/TSD_Rails-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodespacesTryRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <header class="container mx-auto">
      <%= render "shared/menu" %>
    </header>
    <main class="container mx-auto mt-10 px-5">
      <%= yield %>
    </main>
  </body>
</html>

TSD/TSD_Rails-main/app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "contents") do |form| %>
  <%= form.hidden_field :creator_id %>

  <% if recipe.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

TSD/TSD_Rails-main/app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= recipe.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= recipe.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= recipe.content %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this recipe", recipe, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this recipe', edit_recipe_path(recipe), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

TSD/TSD_Rails-main/app/views/recipes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing recipe</h1>

  <%= render "form", recipe: @recipe %>

  <%= link_to "Show this recipe", @recipe, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to recipes", recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

TSD/TSD_Rails-main/app/views/recipes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Recipes</h1>
    <%= link_to 'New recipe', new_recipe_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="recipes" class="min-w-full">
    <%= render @recipes %>
  </div>
</div>

TSD/TSD_Rails-main/app/views/recipes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New recipe</h1>

  <%= render "form", recipe: @recipe %>

  <%= link_to 'Back to recipes', recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

TSD/TSD_Rails-main/app/views/recipes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    
    <% flash.each do |type, message| %>
      <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
    <% end %>

    <% if @recipe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

        <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <%= render @recipe %>

    <%= link_to 'Edit this recipe', edit_recipe_path(@recipe), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this recipe', recipe_path(@recipe), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to recipes', recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

<div class="my-5">
  <h3 class="font-bold text-xl">Ingredients</h3>

  <%= render "ingredients/form", ingredient: @ingredient %>

  <%- @recipe.ingredients.each do |ingredient|%>
    <%= render ingredient %>
    <%= image_tag ingredient.photo if ingredient.photo.attached? %>
  <% end %>
</div>

TSD/TSD_Rails-main/app/views/shared/_menu.html.erb
<nav class="flex items-center justify-between flex-wrap bg-blue-500 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <a href="<%= root_path %>" class="font-semibold text-xl tracking-tight">My Cookbook</a>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      <% menu_items = [
        { name: "Recipes", path: recipes_path },
      ] %>
      <% menu_items.each do |item| %>
        <a href="<%= item[:path] %>" class="block mt-4 lg:inline-block lg:mt-0 text-blue-200 hover:text-white mr-4">
          <%= item[:name] %>
        </a>
      <% end %>
    </div>
    <div>
      <% if user_signed_in? %>
        <span class="inline-block text-sm px-4 py-2 leading-none text-white"><%= current_user.email %></span>
        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-4 lg:mt-0" %>
      <% else %>
        <%= link_to "Log in", new_user_session_path, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-4 lg:mt-0" %>
      <% end %>
    </div>
  </div>
</nav>